{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-data
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
{{- end }}
{{- if .Values.persistence.media.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-media
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  {{- if .Values.persistence.media.storageClass }}
  storageClassName: {{ .Values.persistence.media.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
---
{{- end }}
{{- if .Values.persistence.consume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-consume
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.consume.accessMode }}
  {{- if .Values.persistence.consume.storageClass }}
  storageClassName: {{ .Values.persistence.consume.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.consume.size }}
---
{{- end }}
{{- if .Values.persistence.export.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-export
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.export.accessMode }}
  {{- if .Values.persistence.export.storageClass }}
  storageClassName: {{ .Values.persistence.export.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.export.size }}
{{- end }}

